# -*- coding: utf-8 -*-
"""Tensor_operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJymOpQLwxYgV16XiGgSJHUz3vW5MXJU
"""

import tensorflow as tf

# Step 1: Create a random tensor of shape (4, 6)
t1 = tf.random.uniform(shape=(4, 6),  minval=0, maxval=10, dtype=tf.int64)
print("Tensor of shape(4,6)")
print(t1.numpy())

# Step 2: Find rank and shape
t1_rank = tf.rank(t1)
t1_shape = tf.shape(t1)
print(f"Tensor Rank: {t1_rank.numpy()}, Shape: {t1_shape.numpy()}")

# Step 3: Reshape it into (2, 3, 4) and transpose it to (3, 2, 4)
t2 = tf.reshape(t1, (2, 3, 4))
print(f"Reshaped Tensor Shape: {t2.shape}")
print("Reshaped Tensor:")
print(t2.numpy())

t3 = tf.transpose(t2, perm=[1, 0, 2])

print(f"Transposed Tensor Shape: {t3.shape}")
print("Transposed Tensor:")
print(t3.numpy())

# Step 4: Broadcast a smaller tensor (1, 4) and add to the larger tensor
t4 = tf.random.uniform(shape=(1, 4),  minval=0, maxval=10, dtype=tf.int64)
print("Small Tensor:")
print(t4.numpy())

broadcasted_sum = t3 + t4
print("Broadcasted Sum:")
print(broadcasted_sum.numpy())